name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          push: true
          provenance: false
          tags: |
            ghcr.io/jurajbrabec/simple-app:latest

      - name: Run the Docker container for testing
        run: |
          docker run -d --name test-container ghcr.io/jurajbrabec/simple-app:latest

      - name: Check container status
        run: |
          # wait and check if container is running or exited without error
          sleep 10
          if [ "$(docker inspect -f '{{.State.Running}}' test-container)" != "true" ]; then
            exit_code=$(docker inspect test-container --format='{{.State.ExitCode}}')
            if [ $exit_code -ne 0 ]; then
              echo "Container failed to start (E:${exit_code})."
              exit 1
            fi
          fi
          echo "Container is starting correctly."
          exit 0

      - name: Cleanup Docker container
        run: |
          docker stop test-container
          docker rm test-container
